In [1]:
import sys
print(sys.version)
print(sys.executable)

3.13.12 (tags/v3.13.12:1cbe481, Feb  3 2026, 18:22:25) [MSC v.1944 64 bit (AMD64)]
c:\Users\YogeshwaranVenkatesa\ai-learning\.venv\Scripts\python.exe

In [13]:
item_code='RG-1000'
weight=8.45
purity='22K'
print(f"Item Code: {item_code}")
print(f"Weight: {weight}")
print(f"Purity: {purity}")

Item Code: RG-1000
Weight: 8.45
Purity: 22K

In [12]:
PURITY_FACTORS = {
'22K': 0.916,
'18K': 0.75,
'24K': 0.999
}
def fine_gold(weight,purity):
    return weight * PURITY_FACTORS[purity]

print(fine_gold(10, "22K"))   # should print 9.16

9.16

In [24]:
items = [
    {"code": "RG-1001", "metal": "Gold",   "purity": "22K", "weight": 8.45},
    {"code": "CH-2001", "metal": "Gold",   "purity": "22K", "weight": 24.10},
    {"code": "BG-3001", "metal": "Gold",   "purity": "18K", "weight": 18.30},
    {"code": "RG-1002", "metal": "Silver", "purity": "925", "weight": 6.20},
]

gold_items=[item for item in items if item['metal']=='Gold']
code_items = [item['code'] for item in items]
sum_Value=round(sum(item['weight'] for item in items if item['purity']=='22K'), 2)
print(f"gold_items: {gold_items}")
print(code_items)
print(f"Sum of weights: {sum_Value}")

gold_items: [{'code': 'RG-1001', 'metal': 'Gold', 'purity': '22K', 'weight': 8.45}, {'code': 'CH-2001', 'metal': 'Gold', 'purity': '22K', 'weight': 24.1}, {'code': 'BG-3001', 'metal': 'Gold', 'purity': '18K', 'weight': 18.3}]
['RG-1001', 'CH-2001', 'BG-3001', 'RG-1002']
Sum of weights: 32.55

In [ ]:
PURITY_FACTORS = {"22K": 0.916, "18K": 0.75, "24K": 0.999}
for key,value in PURITY_FACTORS.items():
    print(f"Purity: {key}, Value: {value}")

Purity: 22K, Value: 0.916
Purity: 18K, Value: 0.75
Purity: 24K, Value: 0.999

In [60]:
items = [
    {"code": "RG-1001", "metal": "Gold",   "purity": "22K", "weight": 8.45},
    {"code": "CH-2001", "metal": "Gold",   "purity": "22K", "weight": 24.10},
    {"code": "BG-3001", "metal": "Gold",   "purity": "18K", "weight": 18.30},
    {"code": "RG-1002", "metal": "Silver", "purity": "925", "weight": 6.20},
]
totals = {}
for item in items:
    if item['metal']=='Gold':
        purity = item.get('purity')
        weight = item['weight']
        if purity not in totals:
            totals[purity] = 0
        totals[purity]+=weight
print(totals)

{'22K': 32.55, '18K': 18.3}

In [59]:
with open('test.txt', 'w') as f:
    f.write('Hello, sioniqerp!\n')

with open('test.txt', 'r') as f:
    content = f.read()
print(content)

Hello, sioniqerp!

In [1]:
import pandas as pd
df = pd.read_csv("items.csv")
df

  item_code  category   metal purity  weight_gm      branch
0   RG-1001      Ring    Gold    22K       8.45     Chennai
1   CH-2001     Chain    Gold    22K      24.10     Madurai
2   BG-3001    Bangle    Gold    18K      18.30     Chennai
3   RG-1002      Ring  Silver    925       6.20  Coimbatore
4   NK-4001  Necklace    Gold    22K      42.75     Chennai
5   ER-5001   Earring    Gold    18K       5.60     Madurai
6   BG-3002    Bangle  Silver    925      32.00     Chennai
7   CH-2002     Chain    Gold    24K      10.00  Coimbatore

In [2]:
gold = df[df["metal"] == "Gold"]
gold

  item_code  category metal purity  weight_gm      branch
0   RG-1001      Ring  Gold    22K       8.45     Chennai
1   CH-2001     Chain  Gold    22K      24.10     Madurai
2   BG-3001    Bangle  Gold    18K      18.30     Chennai
4   NK-4001  Necklace  Gold    22K      42.75     Chennai
5   ER-5001   Earring  Gold    18K       5.60     Madurai
7   CH-2002     Chain  Gold    24K      10.00  Coimbatore

In [3]:
gold.groupby("purity")["weight_gm"].sum()

purity
18K    23.9
22K    75.3
24K    10.0
Name: weight_gm, dtype: float64